App\Models\Entities\Car:
  db: documents
  collection: car
  repositoryClass: App\Models\Repositories\CarDocumentRepository
  embedOne:
    dealer:
      targetDocument: App\Models\Entities\Dealer
  fields:
    id:
      type: id
      id: true
    make:
      type: string
      length: 128
    model:
      type: string
      length: 128
    componentry:
      type: string
    price:
      type: int
    vin:
      type: string
      length: 17