version: "3"

services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 'png-webserver'
    restart: 'always'
    ports:
    - "80:80"
    - "443:443"
    links:
    - mysql
    volumes:
    - ${DOCUMENT_ROOT-./src}:/var/www/html
    - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
    - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
    - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      ENV COMPOSER_ALLOW_SUPERUSER: 1
  mysql:
    build: ./bin/mysql
    container_name: 'png-mysql'
    restart: 'always'
    ports:
    - "3306:3306"
    volumes:
    - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
    - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: tan-test
      MYSQL_USER: root
      MYSQL_PASSWORD:
  mongodb:
    container_name: 'png-mongodb'
    image: mongodb:latest
    links:
    - webserver
    ports:
    - "27017:27017"