<?php

namespace TanTest\Http\Response;

use Symfony\Component\HttpFoundation\Response;

/**
 * Class JsonResponse
 * @package App\Http
 */
class JsonResponse extends Response
{
    public function __construct(array $content = [], int $status = 200)
    {
        parent::__construct($content, $status, []);
        $this->headers->set('Content-Type', 'application/json');
    }

    /**
     * @param mixed $content
     * @return Response
     */
    public function setContent($content)
    {
        $content = json_encode($content, JSON_UNESCAPED_UNICODE);
        return parent::setContent($content); // TODO: Change the autogenerated stub
    }
}